name: crunchy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.6.0
  geolocator: ^10.1.0
  permission_handler: ^11.3.1
  http: ^1.2.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2 
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  image_path: "asset/icon.png"

flutter:
  uses-material-design: true

  assets:
    # Logo
    - asset/logo/

    # Cartella per il menu
    - asset/menu/
    
    # Immagine per la mappa
    - asset/mappa/map.png
    
    # Cartella per le foto dei fritti
    - asset/menu/fritti/

    # Cartella per le foto dei panini
    - asset/menu/panini/

    # Cartella per le foto della carne
    - asset/menu/carne/

    # Cartella per le foto dei dolci
    - asset/menu/dolci/

    # Cartella per le foto delle bevande
    - asset/menu/bevande/

  # Cartella per il menu
    - asset/recensioni/

    # Json
    - asset/menu_card.json
    - asset/menu.json

  fonts:
    - family: Playfair Display
      fonts:
        - asset: asset/fonts/PlayfairDisplay-Regular.ttf
        - asset: asset/fonts/PlayfairDisplay-Bold.ttf
          weight: 700