name: Flutter CI

on:
  push:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: flutter-ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze-and-test:
    name: Analyze & Test (unit + integration)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Static analysis
        run: flutter analyze

      - name: Run unit & widget tests
        run: flutter test --dart-define=CI=true

      - name: Run integration tests (flutter-tester)
        run: |
          set -euxo pipefail
          if [ -d "integration_test" ]; then
            flutter test integration_test -d flutter-tester --dart-define=CI=true
          elif [ -d "test/integration_test" ]; then
            flutter test test/integration_test -d flutter-tester --dart-define=CI=true
          else
            echo "No integration tests directory found; skipping integration tests."
          fi

      - name: Generate coverage report
        if: always()
        run: |
          rm -rf coverage
          flutter test --coverage --coverage-path=coverage/lcov.info || true

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info

  build-android:
    name: Build Android (debug)
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build debug APK (if android/ exists)
        run: |
          if [ -d "android" ]; then
            flutter build apk --debug
          else
            echo "No android/ directory; skipping Android build."
          fi

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
